wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: Autoencoder
dataset:
  desc: null
  value: WSI H. pylori
epochs:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.7.4
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699020862.455436
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.4
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
